function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function getGeneratedBy() {
  const keys = ['user', 'currentUser', 'authUser', 'profile'];

  for (const key of keys) {
    const stored = localStorage.getItem(key);
    if (!stored) continue;

    try {
      const user = JSON.parse(stored);
      const name = user.name || user.full_name || user.fullName || user.username || user.email;
      if (name) return name;
    } catch {
      if (stored.length < 80) return stored;
    }
  }

  return localStorage.getItem('username') || 'Current user';
}

function getDocumentStyles() {
  return Array.from(document.styleSheets)
    .map(sheet => {
      try {
        return Array.from(sheet.cssRules).map(rule => rule.cssText).join('\n');
      } catch {
        return '';
      }
    })
    .join('\n');
}

function buildTable(columns, rows) {
  const headers = columns.map(column => `<th>${escapeHtml(column.label)}</th>`).join('');
  const body = rows.map(row => {
    const cells = columns.map(column => {
      const value = typeof column.value === 'function' ? column.value(row) : row[column.value];
      const className = typeof column.className === 'function' ? column.className(row) : column.className;
      return `<td${className ? ` class="${escapeHtml(className)}"` : ''}>${escapeHtml(value || '-')}</td>`;
    }).join('');

    return `<tr>${cells}</tr>`;
  }).join('');

  return `<table><thead><tr>${headers}</tr></thead><tbody>${body}</tbody></table>`;
}

export function exportTablePdf({ title, context, columns, rows, emptyMessage = 'No records to export' }) {
  if (!rows?.length) return false;

  const generatedAt = new Date().toLocaleString();
  const generatedBy = getGeneratedBy();
  const reportTitle = title || 'Ikonex Academy Report';
  const reportContext = context || reportTitle;
  const printWindow = window.open('', '_blank');

  if (!printWindow) return false;

  printWindow.document.write(`
    <!doctype html>
    <html>
      <head>
        <title>${escapeHtml(reportTitle)}</title>
        <style>
          ${getDocumentStyles()}
          @page { margin: 16mm; }
          body { background: #ffffff; color: #2f3542; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          .report-page { max-width: 1120px; margin: 0 auto; }
          .report-brand {
            background: #064e3b;
            color: #ffffff;
            border-radius: 8px;
            padding: 20px 24px;
            margin-bottom: 18px;
          }
          .report-brand h1 { color: #ffffff; font-size: 26px; margin-bottom: 6px; text-transform: uppercase; }
          .report-brand h2 { color: #d1fae5; font-size: 18px; margin-bottom: 0; }
          .report-meta {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 12px;
            margin-bottom: 18px;
          }
          .report-meta div {
            border: 1px solid #e6e8ee;
            border-radius: 8px;
            padding: 12px;
            background: #fbfcfe;
          }
          .report-meta span {
            display: block;
            color: #6b7280;
            font-size: 11px;
            font-weight: 700;
            margin-bottom: 4px;
            text-transform: uppercase;
          }
          .report-meta strong { color: #064e3b; font-size: 13px; }
          .report-card {
            background: #ffffff;
            border: 1px solid #e6e8ee;
            border-radius: 8px;
            padding: 0;
            overflow: hidden;
          }
          .report-card table { page-break-inside: auto; }
          .report-card tr { page-break-inside: avoid; page-break-after: auto; }
          .report-empty { padding: 24px; color: #6b7280; }
          @media print {
            .report-page { max-width: none; }
            .report-card { box-shadow: none; }
            tbody tr:hover { background: transparent; }
          }
        </style>
      </head>
      <body>
        <main class="report-page">
          <section class="report-brand">
            <h1>IKONEX ACADEMY</h1>
            <h2>${escapeHtml(reportTitle)}</h2>
          </section>
          <section class="report-meta">
            <div><span>Report For</span><strong>${escapeHtml(reportContext)}</strong></div>
            <div><span>Date Generated</span><strong>${escapeHtml(generatedAt)}</strong></div>
            <div><span>Generated By</span><strong>${escapeHtml(generatedBy)}</strong></div>
          </section>
          <section class="report-card">
            ${rows.length ? buildTable(columns, rows) : `<p class="report-empty">${escapeHtml(emptyMessage)}</p>`}
          </section>
        </main>
        <script>
          window.addEventListener('load', () => {
            window.focus();
            setTimeout(() => window.print(), 150);
          });
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();

  return true;
}
